{% set name = "diffrax" %}
{% set version = "0.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d8d0ba24bcf8b2556eb47342ef1b623aebde2ac1199d68f4507c87c8b1fcb8bf

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - hatchling
    - pip
  run:
    - python >=3.9
    - equinox >=0.11.2
    - jax >=0.4.28
    - jaxtyping >=0.2.24
    - lineax >=0.0.5
    - optimistix >=0.0.7
    - typeguard ~=2.13.3
    - typing_extensions >=4.5.0

test:
  imports:
    - diffrax
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/patrick-kidger/diffrax
  summary: Numerical differential equation solvers in JAX.
  description: |
    Numerical differential equation solvers in JAX. Autodifferentiable and GPU-capable.
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://docs.kidger.site/diffrax/
  dev_url: https://github.com/patrick-kidger/diffrax

extra:
  recipe-maintainers:
    - maresb
    - dhirschfeld
