{% set name = "diffrax" %}
{% set version = "0.7.0" %}
{% set python_min = "3.10" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f3bcc578cd92a9ca86fc6f5a54c1de76c1ba62f74de69b56002624bf205316f1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - wadler-lindig >=0.1.1
    - python >={{ python_min }}
    - jax >=0.4.38
    - jaxtyping >=0.2.24
    - typing_extensions >=4.5.0
    - typeguard ==2.13.3
    - equinox >=0.11.10
    - lineax >=0.0.5
    - optimistix >=0.0.10

test:
  imports:
    - diffrax
  requires:
    - python {{ python_min }}
    - pip
  commands:
    - pip check

about:
  home: https://github.com/patrick-kidger/diffrax
  summary: Numerical differential equation solvers in JAX.
  description: |
    Numerical differential equation solvers in JAX. Autodifferentiable and GPU-capable.
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://docs.kidger.site/diffrax/
  dev_url: https://github.com/patrick-kidger/diffrax

extra:
  recipe-maintainers:
    - maresb
    - dhirschfeld
