{% set name = "diffrax" %}
{% set version = "0.6.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 50fde010792a2e9d6105fdf2242e024dd779da27c618b56b92c244cd842bd3d1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - jax >=0.4.38
    - jaxtyping >=0.2.24
    - typing_extensions >=4.5.0
    - typeguard ==2.13.3
    - equinox >=0.11.10
    - lineax >=0.0.5
    - optimistix >=0.0.7

test:
  imports:
    - diffrax
  requires:
    - python {{ python_min }}
    - pip
  commands:
    - pip check

about:
  home: https://github.com/patrick-kidger/diffrax
  summary: Numerical differential equation solvers in JAX.
  description: |
    Numerical differential equation solvers in JAX. Autodifferentiable and GPU-capable.
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://docs.kidger.site/diffrax/
  dev_url: https://github.com/patrick-kidger/diffrax

extra:
  recipe-maintainers:
    - maresb
    - dhirschfeld
